language: rust
cache: cargo
rust:
  - stable
env:
  - MCU=stm32l0x1 IO=io-STM32L021 PACKAGE=ufqfpn28
before_script:
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt
script:
  - cd Firmware
  - RUSTFLAGS="-D warnings" cargo build --release --features="rt $MCU $IO $PACKAGE"
  - cd ../Testscripts
  - cargo test -- --nocapture --test-threads=1